// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVNew8iiQVjV8BaGrqxEfu-k2KukDXMw',
    appId: '1:305746890699:web:4dce5b21d50e3ab362304e',
    messagingSenderId: '305746890699',
    projectId: 'authentication-1518e',
    authDomain: 'authentication-1518e.firebaseapp.com',
    storageBucket: 'authentication-1518e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdn2kusSa2JkNzyH4QPJ_GMPinVT3n7XQ',
    appId: '1:305746890699:android:a4814e5030c9f48762304e',
    messagingSenderId: '305746890699',
    projectId: 'authentication-1518e',
    storageBucket: 'authentication-1518e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_OlSowpB4l16_CB7xuHUrFSzpvKU35HQ',
    appId: '1:305746890699:ios:1b0a5b6c405c572f62304e',
    messagingSenderId: '305746890699',
    projectId: 'authentication-1518e',
    storageBucket: 'authentication-1518e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_OlSowpB4l16_CB7xuHUrFSzpvKU35HQ',
    appId: '1:305746890699:ios:1b0a5b6c405c572f62304e',
    messagingSenderId: '305746890699',
    projectId: 'authentication-1518e',
    storageBucket: 'authentication-1518e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUVNew8iiQVjV8BaGrqxEfu-k2KukDXMw',
    appId: '1:305746890699:web:3249e4ea5d14596162304e',
    messagingSenderId: '305746890699',
    projectId: 'authentication-1518e',
    authDomain: 'authentication-1518e.firebaseapp.com',
    storageBucket: 'authentication-1518e.firebasestorage.app',
  );

}