// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkiYuoXN3dBT-ZL8jLFslC9YSahH0xR0',
    appId: '1:177675830046:web:c5da739d396b1ca2ae3f0f',
    messagingSenderId: '177675830046',
    projectId: 'time-capsule-c4c2a',
    authDomain: 'time-capsule-c4c2a.firebaseapp.com',
    storageBucket: 'time-capsule-c4c2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWItaTSR98kZ8_PcDGn2gj8-FmOdboY4',
    appId: '1:177675830046:android:8b4138ac7be603bbae3f0f',
    messagingSenderId: '177675830046',
    projectId: 'time-capsule-c4c2a',
    storageBucket: 'time-capsule-c4c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2ZgH89foet-mI8wgnFGt5F4uYD1G0QQ',
    appId: '1:177675830046:ios:040067d3972335eaae3f0f',
    messagingSenderId: '177675830046',
    projectId: 'time-capsule-c4c2a',
    storageBucket: 'time-capsule-c4c2a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2ZgH89foet-mI8wgnFGt5F4uYD1G0QQ',
    appId: '1:177675830046:ios:040067d3972335eaae3f0f',
    messagingSenderId: '177675830046',
    projectId: 'time-capsule-c4c2a',
    storageBucket: 'time-capsule-c4c2a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkiYuoXN3dBT-ZL8jLFslC9YSahH0xR0',
    appId: '1:177675830046:web:9ac8ca93f20dc848ae3f0f',
    messagingSenderId: '177675830046',
    projectId: 'time-capsule-c4c2a',
    authDomain: 'time-capsule-c4c2a.firebaseapp.com',
    storageBucket: 'time-capsule-c4c2a.firebasestorage.app',
  );

}